### ISSUE TITLE
[bug]无法逆推，每次逆推都报错

### ISSUE THREAD

**Issue by worisur** [xiaolaa2/stable-diffusion-webui-wd14-tagger#4]
环境：
version: [v1.10.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/82a973c04367123ae98bd9abdf80d9eda9b910e2) 
python: 3.10.14
torch: 2.1.2+cu121 
xformers: N/A 
gradio: 3.41.2  
checkpoint: [7c819b6d13](https://google.com/search?q=7c819b6d13663ed720c2254f4fe18373107dfef2448d337913c8fc545640881e)

报错日志：
*** Error completing request
*** Arguments: (<PIL.Image.Image image mode=RGB size=4160x6240 at 0x71518E128F10>, '', False, '', '[name].[output_extension]', 'ignore', False, False, 'wd14-convnext-v2', 0.35, '', '', False, False, True, '0_0, (o)_(o), +_+, +_-, ._., <o>_<o>, <|>_<|>, =_=, >_<, 3_3, 6_9, >_o, @_@, ^_^, o_o, u_u, x_x, |_|, ||_||', False, False) {}
    Traceback (most recent call last):
      File "/home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/modules/call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "/home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/modules/call_queue.py", line 53, in f
        res = func(*args, **kwargs)
      File "/home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/ui.py", line 70, in on_interrogate
        ratings, tags = interrogator.interrogate(image)
      File "/home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/interrogator.py", line 283, in interrogate
        self.load()
      File "/home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/interrogator.py", line 268, in load
        self.model = InferenceSession(str(model_path), providers=providers)
      File "/home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "/home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 480, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/models/wd-tagger/wd-v1-4-convnext-tagger-v2/model.onnx failed:Protobuf parsing failed.

---
Traceback (most recent call last):
  File "/home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1297, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1272, in validate_outputs
    raise ValueError(
ValueError: An event handler (on_interrogate) didn't receive enough output values (needed: 4, received: 3).
Wanted outputs:
    [textbox, label, label, html]
Received outputs:
    [None, "", "<div class='error'>InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/1.worisur/1.tools/1.ai/01.sd/stable-diffusion-webui/models/wd-tagger/wd-v1-4-convnext-tagger-v2/model.onnx failed:Protobuf parsing failed.</div><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>0.0 sec.</span></p><p class='vram'><abbr title='Active: peak amount of video memory used during generation (excluding cached data)'>A</abbr>: <span class='measurement'>2.03 GB</span>, <wbr><abbr title='Reserved: total amount of video memory allocated by the Torch library '>R</abbr>: <span class='measurement'>2.03 GB</span>, <wbr><abbr title='System: peak amount of video memory allocated by all running programs, out of total capacity'>Sys</abbr>: <span class='measurement'>4.7/15.5977 GB</span> (30.2%)</p></div>"]

**Comment by xiaolaa2** [comment]
兄弟，我现在不再搞这个了，你可能需要尝试一下其它人的了，不过看你的报错我个人感觉可能是依赖的版本问题
